on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: checking out repo
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: or13/github-action-js-hello-world@v1.2.12
        with:
          who-to-greet: ${{ secrets.HELLO_WORLD }}
          how-to-greet: ./input.json
          when-to-greet: ./output.json
      - name: cat output of action in filesystem
        run: cat ./output.json
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
